#!/bin/bash

exec 1>> /var/log/autowget.log 2>&1

(cd /path/to/directory && wget -mkpq  http://www.example.org);
mv /path/to/directory/www.example.org/* /path/to/directory/name/you/want;

(cd /path/to/user.github.io/ && git add --all && git commit -m "new mirror" && git push origin master); 

dt=$(date)
echo $dt $HOSTNAME
   

