#!/bin/bash

exec 1>> /var/log/autowget.log 2>&1

wget http://www.example.org/path/to/page -O /path/to/local/repo/where/you/wanna/store/the/file/;

curl -u user:password -T file ftp://server/dir/file; # Uploads via ftp if you're not using Git

dt=$(date)
echo $dt $HOSTNAME
